name: epi2melabs-nf-artic
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - aplanat =0.4.0
    - nextclade-cli =0.13.0
    - np-artic =1.3.0=py_6
    - pomoxis =0.3.6
